config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  post 'reservations/confirm', to: 'reservations#confirm'
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  get 'rooms/index'
  get 'rooms/own', to: 'rooms#own'
  get 'home/index'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :rooms do
    collection do
      get 'search'
   end
  end
  
  resources :users
  
  resources :reservations
  
  resources :rooms do
    resources :reservations
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable
  has_many :rooms
  has_many :reservations
  mount_uploader :user_img, ImageUploader
  validates :username, :email, presence: true 
  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
      flash[:notice_chabge_account] = "アカウント情報を更新しました"
    # 自分で設定した「マイページ」へのパス
    users_account_path(current_user)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(params_profile)
      flash[:notice_chabge_profile] = "プロフィール情報を更新しました"
      redirect_to '/users/profile'
    else
      render "edit"
    end
  end


  private

  def params_profile
    params.require(:user).permit(:user_img, :username, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<h1><%= "#{current_user.username}" %>さんのアカウントページ</h1>

<% if flash[:notice_chabge_account] %>
 <p class="notice"><%= flash[:notice_chabge_account] %></p>
<% end %>

<table>
 <tr>
  <th>メールアドレス</th>
  <td><%= "#{current_user.email}" %></td>
 </tr>

 <tr>
  <th>パスワード</th>
  <td>*********</td>
 </tr>
</table>

<div class="edit_user">
 <%= link_to "アカウント情報を編集する", edit_user_registration_path(current_user), class: "edit_btn" %>
 <%= link_to "プロフィールページ", users_profile_path, class: "user_page" %>
</div>

app/views/users/edit.html.erb
<h3>プロフィール情報の編集</h3>

<%= form_with model: @user do |f| %>
 <table>

 <tr>
  <th><%= f.label :user_img, "画像" %></th>
  <td><%= f.file_field :user_img %></td>
 </tr>

 <tr>
  <th><%= f.label :username, "名前" %></th>
  <td><%= f.text_field :username %></td>
 </tr>

 <tr>
  <th><%= f.label :introduction, "自己紹介" %></th>
  <td><%= f.text_area :introduction %></td>
 </tr>

 </table>

 <div>
  <p><%= f.submit "保存", class: "actions_button" %></p>
  <p><%= link_to "キャンセル", :back, class: "logIn_signUp" %></p>
 </div>
<% end %>

app/views/users/profile.html.erb
<h1><%= "#{current_user.username}" %>さんのプロフィールページ</h1>

<% if flash[:notice_chabge_profile] %>
 <p class="notice"><%= flash[:notice_chabge_profile] %></p>
<% end %>

<table>
 <tr>
  <th>アイコン画像</th>
  <td>
  <% if @user.user_img? %>
      <%= image_tag @user.user_img.url, size: "40x40" %>
       <% else %>
       <%= image_tag "account_icon.png", size: "40x40" %>
      <% end %>
  </td>
 </tr>

 <tr>
  <th>名前</th>
  <td><%= "#{current_user.username}" %></td>
 </tr>

 <tr>
  <th>自己紹介</th>
  <td><%= "#{current_user.introduction}" %></td>
 </tr>
</table>

<div class="edit_user">
 <%= link_to "プロフィール情報を編集する", edit_user_path(current_user), class: "edit_btn" %>
 <%= link_to "アカウントページ", users_account_path, class: "user_page" %>
</div>