config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  post 'reservations/confirm', to: 'reservations#confirm'
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  get 'rooms/index'
  get 'rooms/own', to: 'rooms#own'
  get 'home/index'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :rooms do
    collection do
      get 'search'
   end
  end
  
  resources :users
  
  resources :reservations
  
  resources :rooms do
    resources :reservations
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="main_head">

 <h1 class="headline">Lakelandで新たな世界を旅しよう</h1>

 <div class="form_area">
  <%= form_with(url: search_rooms_path, local: true, method: :get ) do |f| %>
    <%= f.text_field :search_area, placeholder: "エリア名を入力", class: "top_form" %>
    <%= f.submit "検索", class: "top_form_btn" %>
  <% end %>
 </div>

</div>


<div class="recommendation">
 <h3 class="text_area">おすすめのエリア</h3>

 <div class="recommendation_area">

  <div>
    <%= form_with(url: search_rooms_path, local: true, method: :get ) do |f| %>
     <%= f.hidden_field :search_area, value: "東京" %>
     <%= image_submit_tag('tokyo.jpg', class: "image_area") %>
    <% end %>
  </div>

   <div>
    <%= form_with(url: search_rooms_path, local: true, method: :get ) do |f| %>
     <%= f.hidden_field :search_area, value: "京都" %>
     <%= image_submit_tag('kyoto.jpg', class: "image_area") %>
    <% end %>
   </div>
   
   <div>
    <%= form_with(url: search_rooms_path, local: true, method: :get ) do |f| %>
     <%= f.hidden_field :search_area, value: "大阪" %>
     <%= image_submit_tag('osaka.jpg', class: "image_area") %>
    <% end %>
   </div>
   
   <div>
    <%= form_with(url: search_rooms_path, local: true, method: :get ) do |f| %>
     <%= f.hidden_field :search_area, value: "札幌" %>
     <%= image_submit_tag('sapporo.jpg', class: "image_area") %>
    <% end %>
   </div>  
  
 </div>
</div>