config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  post 'reservations/confirm', to: 'reservations#confirm'
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  get 'rooms/index'
  get 'rooms/own', to: 'rooms#own'
  get 'home/index'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :rooms do
    collection do
      get 'search'
   end
  end
  
  resources :users
  
  resources :reservations
  
  resources :rooms do
    resources :reservations
  end

end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :img, ImageUploader
    belongs_to :user
    has_many :reservation
    validates :accommodation, :accommodation_detail, presence: true
    validates :price, presence: true, numericality: true
    validates :address, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @users = User.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    
    if @room.save
      flash[:notice_room] = "施設が作成されました"
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  #ユーザーごとに作成した部屋を表示するためのメソッド
  def own
    @rooms = current_user.rooms
  end

  #検索アクション
  def search
    if !params[:search_keyword].present? || params[:search_area].present?
      @rooms = Room.where('address LIKE(?)', "%#{params[:search_area]}%")
    elsif params[:search_keyword].present?
      @rooms = Room.where('accommodation LIKE(?) OR accommodation_detail LIKE(?)', "%#{params[:search_keyword]}%", "%#{params[:search_keyword]}%")
    else
      @rooms = Room.all
    end
  end

  private

  def room_params
    params.require(:room).permit(:accommodation, :accommodation_detail, :price, :address, :img).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% if flash[:notice_room] %>
 <p class="notice"><%= flash[:notice_room] %></p>
<% end %>

<%= render "shared/partial" %>

<h3>【検索結果】<%= Room.count %>件が見つかりました。</h3>

<table>
   <thead>
     <tr>
       <th>イメージ図</th>
       <th>施設名</th>
       <th>施設紹介</th>
       <th>住所</th>
       <th>料金/日</th>
       <th></th>
     </tr>
   </thead>

   <tbody>
    <% @rooms.each do |room| %>
     <tr>
      <td><%= image_tag room.img.thumb.url, size: '100x100' %></td>
      <td><%= room.accommodation %></td>
      <td><%= room.accommodation_detail %></td>
      <td><%= room.address %></td>
      <td><%= room.price %>/日</td>
      <td><%= link_to "詳細はこちら", room, class: "show_btn" %></td>
     </tr>
    <% end %>
   </tbody>
</table>

app/views/rooms/new.html.erb
<h3>新規登録</h3>

<%= render "shared/error", obj: @room %>

<%= form_with model: @room do |f| %>
 <table>
  <tr>
   <th><%= f.label :accommodation, "施設名" %></th>
   <td><%= f.text_field :accommodation %></td>
  </tr>
  
  <tr>
   <th><%= f.label :accommodation_detail, "施設詳細" %></th>
   <td><%= f.text_area :accommodation_detail, size: "50x5" %></td>
  </tr>

  <tr>
   <th><%= f.label :price, "料金" %></th>
   <td><%= f.number_field :price %></td>
  </tr>

  <tr>
   <th><%= f.label :address, "住所" %></th>
   <td><%= f.text_field :address %></td>
  </tr>

  <tr>
   <th><%= f.label :img, "施設画像" %></th>
   <td><%= f.file_field :img %></td>
  </tr>
 </table>


 <div>
  <p><%= f.submit "保存", class: "actions_button" %></p>
  <p><%= link_to "キャンセル", root_path, class: "logIn_signUp" %></p>
 </div>

<% end %>

app/views/rooms/own.html.erb
<h3>登録済み一覧</h3>

<table>
 <thead>
  <th>画像</th>
  <th>施設名</th>
  <th>紹介文</th>
  <th>料金/日</th>
  <th>作成日</th>
 </thead>

 <tbody>
  <% @rooms.each do |room| %>
   <tr>
    <td><%= image_tag room.img.thumb.url, size: '100x100' %></td>
    <td><%= link_to room.accommodation, room %></td>
    <td><%= room.accommodation_detail %></td>
    <td><%= room.price %>円/日</td>
    <td><%= room.created_at.to_s(:datetime_jp) %></td>
   </tr>
  <% end %>
 </tbody>
</table>

app/views/rooms/search.html.erb
<%= render "shared/partial" %>

<h3>【検索結果】<%= @rooms.count %>件が見つかりました。</h3>

<table>
   <thead>
     <tr>
       <th>イメージ図</th>
       <th>施設名</th>
       <th>施設紹介</th>
       <th>住所</th>
       <th>料金/日</th>
       <th></th>
     </tr>
   </thead>

   <tbody>
    <% @rooms.each do |room| %>
     <tr>
      <td><%= image_tag room.img.thumb.url, size: '100x100' %></td>
      <td><%= room.accommodation %></td>
      <td><%= room.accommodation_detail %></td>
      <td><%= room.address %></td>
      <td><%= room.price %>/日</td>
      <td><%= link_to "詳細はこちら", room, class: "show_btn" %></td>
     </tr>
    <% end %>
   </tbody>
</table>

app/views/rooms/show.html.erb
<%= render "shared/partial" %>

<% if flash[:alert_blank] %>
 <p class="notice"><%= flash[:alert_blank] %></p>
<% end %>

<% if flash[:alert_day] %>
 <p class="notice"><%= flash[:alert_day] %></p>
<% end %>

<% if flash[:alert_number] %>
 <p class="notice"><%= flash[:alert_number] %></p>
<% end %>

<h3><%= link_to "←戻る", :back, class: "back_btn" %></h3>

<div class="show_content">

 <div>
  <%= image_tag @room.img.thumb.url, size: '580x335' %>
 </div>

  <div>
   <%= form_with url: reservations_confirm_path do |f| %>
    <table>
     <%= f.hidden_field :room_id, value: @room.id %>

     <tr>
       <th><%= f.label :name, "施設名" %></th>
       <td><%= @room.accommodation %></td>
     </tr>
 
     <tr>
       <th><%= f.label :price, "値段" %></th>
       <td><%= @room.price %>円/日</td>
       <%= f.hidden_field :price, value: @room.price %>
     </tr>
 
     <tr>
       <th><%= f.label :address, "住所" %></th>
       <td><%= @room.address %></td>
     </tr>
 
     <tr>
       <th><%= f.label :accommodation_detail, "施設紹介" %></th>
       <td><%= @room.accommodation_detail %></td>
     </tr>

     <tr>
       <th><%= f.label :check_in, "チェックイン（必須）" %></th>
       <td><%= f.date_field :check_in %></td>
     </tr>

     <tr>
       <th><%= f.label :check_out, "チェックアウト（必須）" %></th>
       <td><%= f.date_field :check_out %></td>
     </tr>

     <tr>
       <th><%= f.label :number_of_people, "人数（必須）" %></th>
       <td><%= f.number_field :people %></td>
     </tr>
    </table>

    <p><%= f.submit "予約する", class: "reservation_button" %></p>
   <% end %>
  </div>
</div>